In [44]:
import datetime as dt


def RT2RI(date_pre , RT ) :
    Exday = dt.datetime
    pre = date_pre.split("-")
    year = int(pre[0])
    mon = int(pre[1])
    day = int(pre[2])
    # print year , mon , day
    date = Exday(year , mon , day)
        
    if date >= Exday(2015,12,12) :
        if RT >= 35.460 :
            return 0
        elif RT >= 32.397 :
            i = [14.000,32.397,35.460]
            return (i[0]+(RT - i[1])/(i[2] - RT) )           
        elif RT >= 29.153 :
            i = [13.000,29.153,32.397] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 25.751 :
            i = [12.000,25.751,29.153] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 22.199 :
            i = [11.000,22.199,25.751] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )            
        elif RT >= 18.571 :
            i = [10.000,18.571,22.199] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 15.090 :
            i = [9.000,15.090,18.571] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 12.136 :
            i = [8.000,12.136,15.090] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )     
        else :
            i = [7.000,10.028,12.136]
            return (i[0]+(RT - i[1])/(i[2] - RT) )     
        
    elif date >= Exday(2015,11,21):
        if RT >= 34.270 :
            return 0
        elif RT >= 28.491 :
            i = [14.000,28.491,34.270] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )           
        elif RT >= 25.348 :
            i = [13.000,25.348,28.491] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 22.091 :
            i = [12.000,22.091,25.348] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 18.741 :
            i = [11.000,18.741,22.091] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )            
        elif RT >= 15.449 :
            i = [10.000,15.449,18.741] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 12.543 :
            i = [9.000,12.543,15.449] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 10.354 :
            i = [8.000,10.354,12.543] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )     
        else :
            i = [7.000,8.983,10.354] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )     
    
    
    elif date > Exday(2015,11,10) :
        if RT >= 34.326 :
            return 0
        elif RT >= 31.231 :
            i = [14.000,31.231,34.326] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )           
        elif RT >= 27.975 :
            i = [13.000,27.975,31.231] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 24.559 :
            i = [12.000,24.559,27.975] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 20.997 :
            i = [11.000,20.997,24.559] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )            
        elif RT >= 17.390 :
            i = [10.000,17.390,20.997] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 13.997 :
            i = [9.000,13.997,17.390] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 11.215 :
            i = [8.000,11.215,13.997] 
            return (i[0]+(RT - i[1])/(i[2] - RT) )     
        else :
            i = [7.000,9.308,11.215]
            return (i[0]+(RT - i[1])/(i[2] - RT) )     
        
    else :
        # 2015.11.05 column
        if RT >= 34.462 :
            return 0
        elif RT >= 31.362 :
            i = [14.000,31.362,34.462]
            return (i[0]+(RT - i[1])/(i[2] - RT) )           
        elif RT >= 28.109 :
            i = [13.000,28.109,31.362]
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 24.690 :
            i = [12.000,24.690,28.109]
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 21.125 :
            i = [11.000,21.125,24.690]
            return (i[0]+(RT - i[1])/(i[2] - RT) )            
        elif RT >= 17.507 :
            i = [10.000,17.507,21.125]
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 14.100 :
            i = [9.000,14.100 ,17.507]
            return (i[0]+(RT - i[1])/(i[2] - RT) )
        elif RT >= 11.296 :
            i = [8.000,11.296,14.100]
            return (i[0]+(RT - i[1])/(i[2] - RT) )     
        else :
            i = [7.000,9.380 ,11.296]
            return (i[0]+(RT - i[1])/(i[2] - RT) )

In [45]:
import pandas as pd

CAS_re_lt = []

CAS = pd.DataFrame.from_csv("ful_CAS.csv")
for i in CAS.values.tolist() :
    i[4] # RT
    i[10] # Peak_ID
    m = i[10].split("-")
    sample_ID = m[0] + "-" + m[1]
    Time = "2015" + "-" + m[1][:2] + "-" + m[1][2:]
    RI =  RT2RI(Time , i[4]  ) 
    i = i + [RI , sample_ID]
    CAS_re_lt.append(i)

In [62]:
CAS_re = pd.DataFrame(CAS_re_lt)
CAS_re.head()
CAS_re = CAS_re.rename(columns={0: 'Class', 1: 'Sample',2:"Date",3: "Peak",4:"RT", 5: "scan_number",6 :"Intensity",\
                        7 : "Area%", 8 : "CAS_ID", 9 : "Quality",10 : "Peak_ID", 11 : "RI" , 12 : "Sample_ID"})

In [63]:
Retro = CAS_re
del Retro["RT"]
Retro.to_csv("CAS_renext.csv")
Retro.head()

,Class,Sample,Date,Peak,scan_number,Intensity,Area%,CAS_ID,Quality,Peak_ID,RI,Sample_ID
0,CU,CU3,2015/11/03,1,450,104584,0.14,000124-38-9,4.0,CU3-1103-1,6.201155,CU3-1103
1,CU,CU3,2015/11/03,2,493,103807,0.14,000124-38-9,4.0,CU3-1103-2,6.204613,CU3-1103
2,CU,CU3,2015/11/03,3,1981,103443,0.14,000563-46-2,35.0,CU3-1103-3,6.506075,CU3-1103
3,CU,CU3,2015/11/03,3,1981,103443,0.14,000930-18-7,35.0,CU3-1103-3,6.506075,CU3-1103
4,CU,CU3,2015/11/03,3,1981,103443,0.14,000627-20-3,35.0,CU3-1103-3,6.506075,CU3-1103

In [52]:
x = []
CAS_group = CAS_re.groupby("CAS_ID").groups

print "CAS-Group type : ",type(CAS_group)


for cas in CAS_group :
    x.append([cas,CAS_group[cas]])
"~~~~~~~~~~~~~~~~~~show dataframe ~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
test_group_df = pd.DataFrame(x)
test_group_df = test_group_df.rename(columns={0: 'CAS_ID', 1: 'Sample_index'})
# test_group_df
test_group_df.head()

CAS-Group type :  <type 'dict'>

        CAS_ID                                       Sample_index
0  013906-90-6                                             [4109]
1  043145-54-6                                             [9464]
2  000100-52-7  [231, 352, 476, 955, 1147, 1319, 1481, 1660, 1...
3  000194-59-2                        [1520, 11504, 18280, 23571]
4  010422-35-2                                             [1965]

In [54]:
CAS_re.ix[CAS_group["000100-52-7"]]

,Class,Sample,Date,Peak,RT,scan_number,Intensity,Area%,CAS_ID,Quality,Peak_ID,RI,Sample_ID
231,CU,CU3,2015/11/25,34,14.643,3884,14356,0.05,000100-52-7,72.0,CU3-1125-34,11.605459,CU3-1125
352,CU,CU3,2015/12/17,42,17.196,4565,69104,0.10,000100-52-7,43.0,CU3-1217-42,10.531636,CU3-1217
476,CU,CU3,2015/11/07,35,16.053,4260,29045,0.09,000100-52-7,70.0,CU3-1107-35,10.343191,CU3-1107
955,CU,CU4,2015/11/18,42,14.677,3893,56934,0.08,000100-52-7,93.0,CU4-1118-42,9.250645,CU4-1118
1147,CU,CU4,2015/12/17,45,17.204,4567,18095,0.04,000100-52-7,46.0,CU4-1217-45,10.546452,CU4-1217
1319,CU,CU4,2015/11/03,44,16.199,4299,161343,0.21,000100-52-7,43.0,CU4-1103-44,10.604740,CU4-1103
1481,CU,CU4,2015/11/07,41,16.053,4260,57281,0.14,000100-52-7,60.0,CU4-1107-41,10.343191,CU4-1107
1660,CU,CU2,2015/11/14,37,14.820,3931,12307,0.16,000100-52-7,55.0,CU2-1114-37,9.320233,CU2-1114
1871,CU,CU2,2015/11/03,44,16.188,4296,113319,0.36,000100-52-7,90.0,CU2-1103-44,10.583017,CU2-1103
2061,CU,CU2,2015/12/17,39,17.200,4566,33033,0.35,000100-52-7,64.0,CU2-1217-39,10.539023,CU2-1217
2242,CU,CU2,2015/11/07,40,16.061,4262,48927,0.40,000100-52-7,76.0,CU2-1107-40,10.356155,CU2-1107
2646,CU,CU5,2015/11/07,42,16.049,4259,80698,0.27,000100-52-7,45.0,CU5-1107-42,10.336763,CU5-1107
2821,CU,CU5,2015/11/19,42,14.670,3891,47279,0.17,000100-52-7,87.0,CU5-1119-42,9.247426,CU5-1119
3186,CU,CU5,2015/11/03,45,16.184,4295,154244,0.24,000100-52-7,70.0,CU5-1103-45,10.575208,CU5-1103
3537,CU,CU1,2015/11/11,45,16.015,4250,180126,0.41,000100-52-7,60.0,CU1-1111-45,10.467636,CU1-1111
3723,CU,CU1,2015/11/06,43,16.079,4267,73844,0.43,000100-52-7,64.0,CU1-1106-43,10.385854,CU1-1106
3939,CU,CU1,2015/12/17,45,17.200,4566,45432,0.59,000100-52-7,60.0,CU1-1217-45,10.539023,CU1-1217
4361,CU,CU1,2015/11/03,44,16.180,4294,120524,0.20,000100-52-7,87.0,CU1-1103-44,10.567445,CU1-1103
4705,MU,MU1,2015/11/17,44,14.647,3885,31273,0.09,000100-52-7,64.0,MU1-1117-44,9.236967,MU1-1117
4875,MU,MU1,2015/11/07,42,16.057,4261,30294,0.10,000100-52-7,55.0,MU1-1107-42,10.349655,MU1-1107
5050,MU,MU1,2015/11/25,40,14.658,3888,19514,0.04,000100-52-7,64.0,MU1-1125-40,11.673831,MU1-1125
5218,MU,MU3,2015/11/26,41,14.602,3873,43097,0.22,000100-52-7,93.0,MU3-1126-41,11.430933,MU3-1126
5409,MU,MU3,2015/11/03,51,16.195,4298,168315,0.27,000100-52-7,46.0,MU3-1103-51,10.596799,MU3-1103
5571,MU,MU3,2015/11/24,38,14.643,3884,28301,0.22,000100-52-7,62.0,MU3-1124-38,11.605459,MU3-1124
5756,MU,MU3,2015/12/11,45,17.245,4578,156980,0.27,000100-52-7,91.0,MU3-1211-45,11.200535,MU3-1211
5927,MU,MU3,2015/12/21,40,17.189,4563,131201,0.38,000100-52-7,94.0,MU3-1221-40,10.518813,MU3-1221
6041,MU,MU3,2015/11/07,41,16.061,4262,29512,0.17,000100-52-7,64.0,MU3-1107-41,10.356155,MU3-1107
7025,MU,MU5,2015/11/07,42,16.049,4259,45613,0.20,000100-52-7,41.0,MU5-1107-42,10.336763,MU5-1107
7210,MU,MU2,2015/11/06,43,16.098,4272,83543,0.14,000100-52-7,41.0,MU2-1106-43,10.418027,MU2-1106
7386,MU,MU2,2015/11/26,42,14.621,3878,40661,0.07,000100-52-7,83.0,MU2-1126-42,11.509662,MU2-1126
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17056,CR,CR4,2015/11/10,44,16.019,4251,182921,0.13,000100-52-7,50.0,CR4-1110-44,10.289651,CR4-1110
17412,CR,CR4,2015/11/05,42,16.150,4286,97170,0.23,000100-52-7,43.0,CR4-1105-42,10.510685,CR4-1105
17589,CR,CR2,2015/11/21,39,14.643,3884,24402,0.04,000100-52-7,43.0,CR2-1121-39,11.605459,CR2-1121
17743,CR,CR2,2015/11/10,38,16.030,4254,69095,0.08,000100-52-7,42.0,CR2-1110-38,10.306703,CR2-1110
18267,CD,CD1,2015/11/09,44,16.057,4261,88818,0.21,000100-52-7,90.0,CD1-1109-44,10.349655,CD1-1109
18459,CD,CD1,2015/11/06,47,16.090,4270,74037,0.15,000100-52-7,76.0,CD1-1106-47,10.404375,CD1-1106
18804,CD,CD2,2015/11/04,51,16.177,4293,109695,0.15,000100-52-7,81.0,CD2-1104-51,10.561654,CD2-1104
18970,CD,CD2,2015/11/09,48,16.045,4258,372141,1.46,000100-52-7,95.0,CD2-1109-48,10.330369,CD2-1109
19139,CD,CD2,2015/11/06,44,16.091,4270,66715,0.19,000100-52-7,76.0,CD2-1106-44,10.406073,CD2-1106
19300,CD,CD4,2015/11/06,43,16.087,4269,74114,0.12,000100-52-7,70.0,CD4-1106-43,10.399296,CD4-1106
19645,CD,CD4,2015/11/18,44,14.643,3884,241248,0.65,000100-52-7,95.0,CD4-1118-44,9.235166,CD4-1118
19820,CD,CD4,2015/11/09,45,16.068,4264,110781,0.19,000100-52-7,60.0,CD4-1109-45,10.367616,CD4-1109
19994,CD,CD6,2015/11/18,44,14.659,3888,141501,0.36,000100-52-7,96.0,CD6-1118-44,9.242402,CD6-1118
20174,CD,CD6,2015/12/12,46,17.204,4567,817100,4.26,000100-52-7,95.0,CD6-1212-46,10.546452,CD6-1212
20360,CD,CD6,2015/11/23,42,14.609,3875,199386,0.87,000100-52-7,96.0,CD6-1123-42,11.459524,CD6-1123
20719,CD,CD6,2015/11/06,45,16.083,4268,128638,0.21,000100-52-7,92.0,CD6-1106-45,10.392556,CD6-1106
20884,CD,CD6,2015/11/09,43,16.053,4260,151797,0.20,000100-52-7,81.0,CD6-1109-43,10.343191,CD6-1109
21076,CD,CD6,2015/12/21,48,17.181,4561,554465,3.48,000100-52-7,96.0,CD6-1221-48,10.504317,CD6-1221
21254,CD,CD3,2015/11/06,44,16.079,4267,240755,0.31,000100-52-7,95.0,CD3-1106-44,10.385854,CD3-1106
21418,CD,CD3,2015/11/09,46,16.057,4261,392085,0.36,000100-52-7,95.0,CD3-1109-46,10.349655,CD3-1109
21583,CD,CD3,2015/11/04,46,16.169,4291,285277,0.32,000100-52-7,95.0,CD3-1104-46,10.546338,CD3-1104
21742,CD,CD7,2015/11/09,41,16.068,4264,99600,0.14,000100-52-7,76.0,CD7-1109-41,10.367616,CD7-1109
21915,CD,CD7,2015/11/06,41,16.083,4268,122098,0.23,000100-52-7,90.0,CD7-1106-41,10.392556,CD7-1106
22089,CD,CD7,2015/11/23,43,14.602,3873,183323,0.93,000100-52-7,96.0,CD7-1123-43,11.430933,CD7-1123
22276,CD,CD7,2015/11/18,44,14.625,3879,683119,2.09,000100-52-7,96.0,CD7-1118-44,9.227125,CD7-1118
22460,CD,CD7,2015/12/18,45,17.178,4560,337495,1.73,000100-52-7,96.0,CD7-1218-45,10.498923,CD7-1218
22829,CD,CD7,2015/12/12,44,17.211,4569,189196,0.91,000100-52-7,96.0,CD7-1212-44,10.559559,CD7-1212
23030,CD,CD5,2015/11/18,48,14.674,3892,117611,0.18,000100-52-7,93.0,CD5-1118-48,9.249264,CD5-1118
23195,CD,CD5,2015/11/23,43,14.617,3877,112729,0.23,000100-52-7,93.0,CD5-1123-43,11.492788,CD5-1123
23546,CD,CD5,2015/11/06,45,16.090,4270,73729,0.08,000100-52-7,47.0,CD5-1106-45,10.404375,CD5-1106

In [55]:
import numpy as np
from sklearn.cluster import MeanShift, estimate_bandwidth


def MeanScan(CAS_ID, cas_index_list , scan_list , bandwidth ) :
    # Y has index number of data frame
    Y = np.array(zip(cas_index_list,np.zeros(len(cas_index_list))), dtype=np.int)    
    X = np.array(zip(scan_list,np.zeros(len(scan_list))), dtype=np.int)
    ms = MeanShift(bandwidth=bandwidth, bin_seeding=True)
    ms.fit(X)
    # label of item
    labels = ms.labels_
    cluster_centers = ms.cluster_centers_
    labels_unique = np.unique(labels)
    n_clusters_ = len(labels_unique)
    # Let be check
    result = []
    for k in range(n_clusters_):
        my_members = labels == k
        result.append( [CAS_ID , k , list(Y[my_members, 0]) , list(X[my_members, 0])] )
        # CAS-ID  / sub cluster / dataframe index / real scan value
    return result